import type { MockGradedCard } from "@/lib/card-filters/types"

/** Demo catalog used when Supabase is unavailable or the live pool is empty. */
export const MOCK_GRADED_CARDS: MockGradedCard[] = [
  {
    id: "demo-1",
    cardId: "demo-1",
    title: "Charizard Base Set Holo",
    price: 4200,
    popCount: 412,
    grade: "PSA 10",
    image: "/placeholder.svg",
    popSource: "demo",
  },
  {
    id: "demo-2",
    cardId: "demo-2",
    title: "Pikachu Illustrator Promo",
    price: 4800,
    popCount: 39,
    grade: "PSA 9",
    image: "/placeholder.svg",
    popSource: "demo",
  },
  {
    id: "demo-3",
    cardId: "demo-3",
    title: "Umbreon VMAX Alt Art",
    price: 680,
    popCount: 1840,
    grade: "PSA 10",
    image: "/placeholder.svg",
    popSource: "demo",
  },
  {
    id: "demo-4",
    cardId: "demo-4",
    title: "Lugia Neo Genesis 1st Ed",
    price: 3100,
    popCount: 88,
    grade: "PSA 10",
    image: "/placeholder.svg",
    popSource: "demo",
  },
  {
    id: "demo-5",
    cardId: "demo-5",
    title: "Rayquaza VMAX Alt Art",
    price: 520,
    popCount: 920,
    grade: "PSA 9",
    image: "/placeholder.svg",
    popSource: "demo",
  },
  {
    id: "demo-6",
    cardId: "demo-6",
    title: "Gengar Fossil Holo",
    price: 890,
    popCount: 156,
    grade: "BGS 9.5",
    image: "/placeholder.svg",
    popSource: "demo",
  },
  {
    id: "demo-7",
    cardId: "demo-7",
    title: "Mewtwo GX Shining",
    price: 240,
    popCount: 67,
    grade: "PSA 10",
    image: "/placeholder.svg",
    popSource: "demo",
  },
  {
    id: "demo-8",
    cardId: "demo-8",
    title: "Blastoise Base Set Holo",
    price: 1750,
    popCount: 523,
    grade: "PSA 9",
    image: "/placeholder.svg",
    popSource: "demo",
  },
  {
    id: "demo-9",
    cardId: "demo-9",
    title: "Mew Gold Star",
    price: 3900,
    popCount: 14,
    grade: "PSA 10",
    image: "/placeholder.svg",
    popSource: "demo",
  },
  {
    id: "demo-10",
    cardId: "demo-10",
    title: "Espeon VMAX Alt Art",
    price: 410,
    popCount: 2100,
    grade: "CGC 10",
    image: "/placeholder.svg",
    popSource: "demo",
  },
  {
    id: "demo-11",
    cardId: "demo-11",
    title: "Alakazam Base Set Holo",
    price: 620,
    popCount: 301,
    grade: "PSA 8",
    image: "/placeholder.svg",
    popSource: "demo",
  },
  {
    id: "demo-12",
    cardId: "demo-12",
    title: "Gyarados Skyridge Holo",
    price: 2800,
    popCount: 42,
    grade: "BGS 10",
    image: "/placeholder.svg",
    popSource: "demo",
  },
  {
    id: "demo-13",
    cardId: "demo-13",
    title: "Venusaur Base Set Holo",
    price: 980,
    popCount: 445,
    grade: "PSA 9",
    image: "/placeholder.svg",
    popSource: "demo",
  },
  {
    id: "demo-14",
    cardId: "demo-14",
    title: "Dragonite Skyridge Holo",
    price: 1550,
    popCount: 118,
    grade: "PSA 10",
    image: "/placeholder.svg",
    popSource: "demo",
  },
  {
    id: "demo-15",
    cardId: "demo-15",
    title: "Machamp Base Set Holo",
    price: 180,
    popCount: 8900,
    grade: "PSA 8",
    image: "/placeholder.svg",
    popSource: "demo",
  },
]
